name    'saheba-sinopia'
version '1.0.3'
source 'https://github.com/saheba/puppet-sinopia.git'
author 'saheba'
license 'ASL'
summary 'Module to manage sinopia installations'
description 'Module to manage sinopia installations, for details see https://github.com/rlidwka/sinopia'
project_page 'https://github.com/saheba/puppet-sinopia'
dependency 'willdurand/nodejs', '>= 1.6.5'
